const FILTER_TEAM = "FILTER_TEAM";
const FILTER_PLATFORM = "FILTER_PLATFORM";
const ORDER_NAME = "ORDER_NAME";
const ORDER_DATE = "ORDER_DATE"
const SET_DRIVERS = "SET_DRIVERS"
const RESET = "RESET"
const SEARCH = "SEARCH"
const NUMBER = "NUMBER"

export {NUMBER, SEARCH, RESET, FILTER_PLATFORM,FILTER_TEAM , ORDER_DATE, ORDER_NAME, SET_DRIVERS }